name: dockerfiles

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # format: minute hour day-of-month month day-of-week
    # Setting to 2 because base images are built on 1
    - cron: "0 0 2 * *"
  push:
    branches:
      - "master"
    paths:
      - "dockerfiles/**"
      - ".github/workflows/update_docker.yml"

jobs:
  ros:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile: ["deepracer_joy", "deepracer_ros1_bridge", "deepracer_ros2"]
    steps:
      - uses: actions/checkout@v2
      - name: Update date
        run: |
          echo "::set-env name=TODAY::$(date +'%Y-%m-%d')"
      - name: Build and publish docker image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: athackst/${{ matrix.dockerfile }}
          dockerfile: dockerfiles/${{ matrix.dockerfile }}.dockerfile
          path: dockerfiles
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest,${{ env.TODAY }}
          labels: version=${{ env.TODAY }}
